JacobDomagala/StaticAnalysis

README.md, action.yml, entrypoint.sh, run_static_analysis.py
=> Add input variable to set CPPCHECK args

Dockerfile, README.md, action.yml, docker/static_analysis.dockerfile, entrypoint.sh, run_static_analysis.py
=> 7: Add option to run static analysis only on files changed in PR. 10: Bump the versions of Cppcheck and clang-tidy

README.md, action.yml, entrypoint.sh
=> 9: Add action input for additional CMake args

run_static_analysis.py
=> 12: Check for file length when creating code snippet

docker/static_analysis.dockerfile, entrypoint.sh
=> [#14]: Update to clang-12

docker/static_analysis.dockerfile
=> [#21]: Update cppcheck to version 2.5

entrypoint.sh, run_static_analysis.py
=> [#23]: Fix excluding directories for clang-tidy

run_static_analysis.py
The result of .lower() will never be "True".
Signed-off-by: Sean Robinson <sean.robinson@scottsdalecc.edu>
=> Simplify INPUT_VERBOSE check

entrypoint.sh
As this was consistently misspelled, the variable behaved as intended.
Signed-off-by: Sean Robinson <sean.robinson@scottsdalecc.edu>
=> Fix misspelled variable

entrypoint.sh, get_files_to_check.py
=> 33: Fix issue with multiple files

entrypoint.sh
=> [#35]: Fix wrong prefix used to determine excluded directory

entrypoint.sh, get_files_to_check.py
=> 37: Rewrite get_files_to_check.py

entrypoint.sh
Signed-off-by: Sean Robinson <sean.robinson@scottsdalecc.edu>
=> Escape quotes inside quotes for debug_print of files_to_check

entrypoint.sh
The init_script may want to make changes in the PR tree context.
Signed-off-by: Sean Robinson <sean.robinson@scottsdalecc.edu>
=> Run init_script after checking out PR tree

docker/static_analysis.dockerfile, entrypoint.sh
=> [#44]: Update docker image (with clang-tidy and cppcheck)

src/run_static_analysis.py, test/test_static_analysis.py
=> 48: Fix issue with consecutive `Note`s

action.yml, src/get_files_to_check.py, test/test_static_analysis.py
=> 41: Allow user to pass multiple exclude dirs

action.yml
=> 52: Shorten action.yml description so it fits in 125 chars

.github/workflows/test_action.yml, .github/workflows/tests.yml, .github/workflows/unit_tests.yml, docker/static_analysis.dockerfile, entrypoint.sh
=> [#54]: Update docker image

.github/workflows/linter.yml, .github/workflows/test_action.yml, .github/workflows/unit_tests.yml
=> [#59]: Allow workflows to run on push to master

README.md
=> [#58]: Add build badges to README

.github/workflows/linter.yml, .github/workflows/test_action.yml, .github/workflows/unit_tests.yml
=> [#64]: Add new step in test_action for outputting the results

.github/workflows/test_action.yml
=> [#66]: Cleanup `TestAction` workflow

.gitignore, test/test_static_analysis.py, test/utils/DummyFile.cpp, test/utils/DummyFile.hpp, test/utils/dummy_project/DummyFile.cpp, test/utils/dummy_project/DummyFile.hpp, test/utils/helper_functions.py
=> [#50]: Add more unittests

entrypoint.sh
=> [#72]: Create and change dir to build before running init_script

entrypoint.sh
=> [#74]: Fix incorrect path to init_script

action.yml, entrypoint.sh
=> [#76]: Don't change directory to build when running init_script

entrypoint.sh
=> [#80]: Fix cppcheck command

README.md
=> [#84]: Update README

README.md
=> [#86]: Add hyperlinks to README

.github/workflows/shellcheck.yml, entrypoint.sh
=> [#88]: Add shellcheck action

entrypoint.sh
=> [#101] Fix the case with empty preselected files

entrypoint.sh
=> [#98]: Speedup `cppcheck`

src/run_static_analysis.py, test/test_static_analysis.py
=> [#110]: Remove duplicates

action.yml
=> [#114]: Update Marketplace info

Dockerfile, docker/static_analysis.dockerfile, entrypoint_cpp.sh, llvm.sh
=> [#116]: Update tools

action.yml
=> [#118]: 007 🍸  release

src/sa_utils.py
=> [#130]: Fix issue with tools reporting lines 0:0
